version: '3'
services:
  node1: 
      build: .
      cap_add: 
        - ALL 
      volumes:
        - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      command: bitcoind  -testnet  -server  -listen   -rpcuser=rpc -rpcpassword=x  -rpcport=10345 -port=12333 -addnode=10.7.0.1:12333 -addnode=10.7.0.2:12333 -addnode=10.7.0.3:12333 -addnode=10.7.0.4:12333 -addnode=10.7.0.5:12333 
      networks:
        vpcbr:
          ipv4_address: 10.7.0.2
      ports:
          - "12342:12333"


  node2: 
      build: .
      cap_add: 
        - ALL 
      volumes:
        - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      command: bitcoind  -testnet  -server  -listen   -rpcuser=rpc -rpcpassword=x  -rpcport=10345 -port=12333 -addnode=10.7.0.1:12333 -addnode=10.7.0.2:12333 -addnode=10.7.0.3:12333 -addnode=10.7.0.4:12333 -addnode=10.7.0.5:12333 
      networks:
        vpcbr:
          ipv4_address: 10.7.0.3
      ports:
          - "12343:12333"


  node3: 
      build: .
      cap_add: 
        - ALL 
      volumes:
        - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      command: bitcoind  -testnet  -server  -listen   -rpcuser=rpc -rpcpassword=x  -rpcport=10345 -port=12333 -addnode=10.7.0.1:12333 -addnode=10.7.0.2:12333 -addnode=10.7.0.3:12333 -addnode=10.7.0.4:12333 -addnode=10.7.0.5:12333 
      networks:
        vpcbr:
          ipv4_address: 10.7.0.4
      ports:
          - "12344:12333"


  node4: 
      build: .
      cap_add: 
        - ALL 
      volumes:
        - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      command: bitcoind  -testnet  -server  -listen   -rpcuser=rpc -rpcpassword=x  -rpcport=10345 -port=12333 -addnode=10.7.0.1:12333 -addnode=10.7.0.2:12333 -addnode=10.7.0.3:12333 -addnode=10.7.0.4:12333 -addnode=10.7.0.5:12333 
      networks:
        vpcbr:
          ipv4_address: 10.7.0.5
      ports:
          - "12345:12333"


  node5: 
      build: .
      cap_add: 
        - ALL 
      volumes:
        - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      command: bitcoind  -testnet  -server  -listen   -rpcuser=rpc -rpcpassword=x  -rpcport=10345 -port=12333 -addnode=10.7.0.1:12333 -addnode=10.7.0.2:12333 -addnode=10.7.0.3:12333 -addnode=10.7.0.4:12333 -addnode=10.7.0.5:12333 
      networks:
        vpcbr:
          ipv4_address: 10.7.0.6
      ports:
          - "12346:12333"


networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.7.0.0/16